version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Post-build started on `date`
      - ./gradlew javadoc assembleDist
artifacts:
  type: zip
  files:
    - 'build/**/distributions/pact-jvm-server_*.zip'
  discard-paths: yes
